### ISSUE TITLE
Can't find anything with blueprint strings?

### ISSUE THREAD

**Issue by MrIHH** [Oarcinae/FactorioScenarioMultiplayerSpawn#10]
I like to think I'm not an idiot, but a normal blueprint mod shows up in the top left.  All I have is "Tag" and "Spawn" but nothing about a blueprint.  Am I missing something?

**Comment by MrIHH** [comment]
And yes, it's set to "True"

**Comment by Oarcinae** [comment]
Old bug probably, sorry I didn't see it before, but marking as closed since I'm removing BPS for 0.15 changes.
