### ISSUE TITLE
Resource Spawning Error

### ISSUE THREAD

**Issue by polo123qwe** [Oarcinae/FactorioScenarioMultiplayerSpawn#103]
I was trying to set up a multiplayer spawn with Angels ores but upon setting the fifth resource it never spawns, does not matter which ore is set. Tested in two different machines with the same result.
Running Factorio version 0.17.58
Mods: RSO (using vanilla biters), all Bob's mods and Angels refining.

<img width="348" alt="image" src="https://user-images.githubusercontent.com/8913727/62946618-543bb080-bde1-11e9-84bf-1be5124ad92e.png">
Starting a server with those settings results in coal not appearing in the spawn

**Comment by Oarcinae** [comment]
I'll have to take a look at it. To be honest, I don't maintain the mod very well.
Just curious, is there a reason you prefer to use the mod versus the scenario?
I always recommend using the scenario if possible.

**Comment by polo123qwe** [comment]
The interface makes it easier to tweak the settings and since we were trying in various machines it was easier to sync the mod than to have to manually install the scenario

**Comment by Oarcinae** [comment]
Yep, fair enough.

I won't have to time to get to this for at least a few days since I've been travelling and otherwise busy.

Either way, I'd recommend trying out the scenario version while waiting since that includes a lot of newer changes and improvements.

I'll post an update here once I get a chance to update the mod version.

**Comment by polo123qwe** [comment]
Well we are playing with the workaround we found, which is to use the oil spawn to spawn various (5) very rich ore paths of 1x1. Which works just fine

**Comment by Oarcinae** [comment]
Closing since I'm not going to maintain the mod version anymore.
