### ISSUE TITLE
Is there a way to disable regrowth mod on client hosted game?

### ISSUE THREAD

**Issue by Trilient** [Oarcinae/FactorioScenarioMultiplayerSpawn#107]
Title pretty much explains it. Would like to disable regrowth on an existing game without starting over, I've tried editing the save file config but even if I try overwriting it with a duplicate zip save file it doesn't work. It's been deleting segments of our train tracks before we can get them up and running, probably due to the distance.

**Comment by Oarcinae** [comment]
Hi, that shouldn't happen anymore with the recent update so I'm assuming it's the same bug from an older version.

To stop it during run time do this:
/c global.ocfg.enable_regrowth=false

**Comment by Oarcinae** [comment]
I'm going to close this as solved, please re-open if you're still having issues. @Trilient
