### ISSUE TITLE
Crash on first start

### ISSUE THREAD

**Issue by 74656b** [Oarcinae/FactorioScenarioMultiplayerSpawn#114]
Windows Server 2019 1809
Factorio 0.17.79

Brand new setup of a server, followed wiki option 3(mostly).

   1.517 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "First argument must be a number, table or string. Got: nil
stack traceback:
	D:/Factorio/temp/currently-playing/control.lua:406: in main chunk
stack traceback:
	[C]: in function 'on_event'
	D:/Factorio/temp/currently-playing/control.lua:406: in main chunk"

[factorio-current.log](https://github.com/Oarcinae/FactorioScenarioMultiplayerSpawn/files/4332211/factorio-current.log)
[config.txt](https://github.com/Oarcinae/FactorioScenarioMultiplayerSpawn/files/4332220/config.txt)

**Comment by Oarcinae** [comment]
Hey @74656b my guess is that there's something in 0.18 that isn't compatible with 0.17.79.

Can you try this version: https://github.com/Oarcinae/FactorioScenarioMultiplayerSpawn/releases/tag/0.17_STABLE ?

And just to confirm, you attached a config.txt but your actual file on the server is config.lua right?

**Comment by 74656b** [comment]
Will test now and report back, yes the file on the server is .lua, Github complained!

**Comment by 74656b** [comment]
Using the provided release everything is working smoothly.

Thank you!

**Comment by Oarcinae** [comment]
Awesome good to hear! Sorry about not updating the releases/tags. Hopefully the new readme and releases should help guide others.
