### ISSUE TITLE
Is there an easy way to override bridge=true on moat creation?

### ISSUE THREAD

**Issue by bplein** [Oarcinae/FactorioScenarioMultiplayerSpawn#117]
I upgraded to the new 0.18 version and was surprised by the moat bridge creation. Is there an easy way to override this from config.lua vs. hand-editing separate_spans.lua?

**Comment by Oarcinae** [comment]
Hah yeah... sorry about that. There should be a config for that but at this point there are so many config options I just didn't bother exposing it.

The quick fix is go into separate_spawns.lua and edit this one line:
`CreateMoat(surface, spawn.pos, chunkArea, global.ocfg.spawn_config.gen_settings.land_area_tiles, "water", true)` change it to `false`

`CreateMoat(surface, spawn.pos, chunkArea, global.ocfg.spawn_config.gen_settings.land_area_tiles, "water", false)`

**Comment by bplein** [comment]
Thanks. That's where I found it earlier, and I've done that for now. 

I appreciate your quick response.
