### ISSUE TITLE
Starter crashed ship has spidertron and no setting in the config.lua

### ISSUE THREAD

**Issue by Oarcinae** [Oarcinae/FactorioScenarioMultiplayerSpawn#125]
Need to remove or add a config option and disable by default.

**Comment by bplein** [comment]
As long as we are moving items from LUA hard coded to config options:

1) Crash ship contents (all, not just spidertron)
2) Bridging of moat is set to TRUE on moat creation. Bridge should be a config option

**Comment by Oarcinae** [comment]
Will do.
