### ISSUE TITLE
Undecorator deletes fish

### ISSUE THREAD

**Issue by bplein** [Oarcinae/FactorioScenarioMultiplayerSpawn#126]
Undecorator runs RemoveFish() which means you can't build spidertrons.

I have remmed out the RemoveFish function call from inside the Undecorator code, but this should either be removed or a separate config option.

**Comment by Ice-Cue** [comment]
you can get fish by sending  the white sience pack with the rocket to the space. thats the new game mechanic in 1.0

**Comment by bplein** [comment]
@Ice-Cue while that's interesting, it doesn't change the request. Removing Fish should be a separate config variable.

**Comment by silasary** [comment]
Fish are useful for early-game healing.  They should definitely be a separate setting.

**Comment by Oarcinae** [comment]
I'm just going to drop the fish removal entirely and leave undecorator. I can't imagine that at this point people would use or care about that as a specific setting.
