### ISSUE TITLE
server crash with the ney version 1.1.19

### ISSUE THREAD

**Issue by Ice-Cue** [Oarcinae/FactorioScenarioMultiplayerSpawn#127]
`2189.039 Error MainLoop.cpp:1285: Exception at tick 121492: The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_gui_selected_tab_changed (ID 145)
...iles/temp/currently-playing/lib/separate_spawns_guis.lua:551: attempt to index field 'uniqueSpawns' (a nil value)
stack traceback:
	...iles/temp/currently-playing/lib/separate_spawns_guis.lua:551: in function '?'
	...serverfiles/temp/currently-playing/lib/oarc_gui_tabs.lua:247: in function 'SetOarGuiTabContent'
	...serverfiles/temp/currently-playing/lib/oarc_gui_tabs.lua:149: in function 'TabChangeOarcGui'
	...server_02/serverfiles/temp/currently-playing/control.lua:192: in function <...server_02/serverfiles/temp/currently-playing/control.lua:191>
2189.041 Error ServerMultiplayerManager.cpp:91: MultiplayerManager failed: "The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_gui_selected_tab_changed (ID 145)
...iles/temp/currently-playing/lib/separate_spawns_guis.lua:551: attempt to index field 'uniqueSpawns' (a nil value)
stack traceback:
	...iles/temp/currently-playing/lib/separate_spawns_guis.lua:551: in function '?'
	...serverfiles/temp/currently-playing/lib/oarc_gui_tabs.lua:247: in function 'SetOarGuiTabContent'
	...serverfiles/temp/currently-playing/lib/oarc_gui_tabs.lua:149: in function 'TabChangeOarcGui'
	...server_02/serverfiles/temp/currently-playing/control.lua:192: in function <...server_02/serverfiles/temp/currently-playing/control.lua:191>"
2189.041 Info ServerMultiplayerManager.cpp:780: updateTick(121492) changing state from(InGame) to(Failed)
2189.041 Quitting: multiplayer error.
2189.147 Info ServerMultiplayerManager.cpp:140: Quitting multiplayer connection.
2189.147 Info ServerMultiplayerManager.cpp:780: updateTick(4294967295) changing state from(Failed) to(Closed)
2189.147 Info HttpSharedState.cpp:54: Downloading https://multiplayer.factorio.com/remove-game/9049409
2189.519 Info UDPSocket.cpp:218: Closing socket
2189.519 Info UDPSocket.cpp:248: Socket closed
2189.519 Info UDPSocket.cpp:218: Closing socket
2189.599 Info UDPSocket.cpp:218: Closing socket
2189.599 Info UDPSocket.cpp:248: Socket closed
2189.600 Goodbye`

i created for the new Factorio Version a new map. i get randomly errors and the server is crashing.

**Comment by bplein** [comment]
I have 2 OARCs running, one with shared chests/power and one without. Both were created before 1.1.19 and both run fine with 1.1.19.

**Comment by Oarcinae** [comment]
@Ice-Cue Is this still happening? I'm not sure I changed much recently that would cause this type of issue.

**Comment by Oarcinae** [comment]
Closing since I haven't heard back more about this. Feel free to reopen if it comes back.
