### ISSUE TITLE
Abandoned base

### ISSUE THREAD

**Issue by Gastarbeiter** [Oarcinae/FactorioScenarioMultiplayerSpawn#13]
Resources are not generated and spawn is not cleared if player leaves the game in <1 sec after choosing solo spawn

**Comment by Oarcinae** [comment]
Commented on the pull request. I have a planned fix for this, need to test. Basically I don't want to remove the global var that the generation depends upon.

**Comment by Oarcinae** [comment]
This should be fixed but needs testing.
