### ISSUE TITLE
Scenario crashes on_tick if it is (incorrectly) set up with energy_sharing = true & coin_shop = false

### ISSUE THREAD

**Issue by silasary** [Oarcinae/FactorioScenarioMultiplayerSpawn#130]
`shared_chests.SharedEnergyStoreInputOnTick` attempts to run, but `global.oshared` has never been initialized, so it throws an error on shared_chests.lua:89

This obviously comes from a bad configuration, but it should be more clear as to why the game is crashing.

**Comment by Oarcinae** [comment]
@silasary Which configuration settings caused this specifically?
