### ISSUE TITLE
Hopefully it will be compatible with space exploration

### ISSUE THREAD

**Issue by anye77** [Oarcinae/FactorioScenarioMultiplayerSpawn#135]
It is a very creative scene, but unfortunately it is incompatible with space exploration. I tried to close the configuration of the rocket silo, but failed. The scientific research of space exploration has been removed, so I hope it can be used together

**Comment by Oarcinae** [comment]
@anye77 Yeah unfortunately that mod is a big overhaul and a LOT of things conflict with this scenario so it's unlikely to ever be compatible :( Sorry!

**Comment by Oarcinae** [comment]
Closing since this won't be done.
