### ISSUE TITLE
Mod incompatiabilities with level::on_player_created

### ISSUE THREAD

**Issue by SquirrelKiev** [Oarcinae/FactorioScenarioMultiplayerSpawn#140]
Haven't looked into it properly, but mods that use on_player_created (or something related to forces) seem to crash the game?
Known mods with this issue are Improved Research Queue, Helmod. 
![image](https://user-images.githubusercontent.com/41798511/209570975-b6ea11f8-20b6-4140-8959-8ab739188b46.png)

**Comment by Oarcinae** [comment]
@SquirrelKiev Thanks for reporting this, I'm not sure what might be conflicting here...

Let me know if you figure anything out. I don't play Factorio anymore and don't have the time to debug this.
If anyone else knows what might be causing this, let me know and I'll see what I can do.

**Comment by Oarcinae** [comment]
This will be fixed in the upcoming 2.0 release since it will now be a proper mod, I can set the dependencies correctly (it was a mod load order issue). I just tested it and was able to both repro and fix the issue. Will close this once I release.

**Comment by SquirrelKiev** [comment]
A welcome suprise to see this get fixed! Thank you for looking into this
