### ISSUE TITLE
PvP

### ISSUE THREAD

**Issue by asmaps** [Oarcinae/FactorioScenarioMultiplayerSpawn#15]
So #2  means there will be no PvP possible?
Imho this scenario would be perfect start for PvP mode... and it's awesome with this map in terms that people don't have to install mods to be able to join.

I'd be glad to help coding, but as I'm not a big lua expert and didn't try to build a factorio mod/scenario before I don't really know where to start.
Can you give me some tips how the problem could maybe be solved and "best practices" for developing factorio stuff?

**Comment by Oarcinae** [comment]
There's a PvP mode in 0.15. Have you tried it?

I have no problem helping out if you're interested in forking mine.

I do plan to introduce team capabilities soon though. I only plan on supporting PvE (all teams friendly) but I think once I am done with that, it wouldn't be too hard to modify for PvP.

The most annoying part for me is the GUI work to be honest.

**Comment by Oarcinae** [comment]
Closing since I don't plan to implement PvP.
