### ISSUE TITLE
blueprintstring folder not present in locale.

### ISSUE THREAD

**Issue by Wolftein** [Oarcinae/FactorioScenarioMultiplayerSpawn#16]
I had to download a previous locale version (the one before the 0.15 compatibility commit), maybe add some release files for version 0.14?

**Comment by Oarcinae** [comment]
Can you check if it's fixed now? I was messing around with dev branch stuff. I am intentionally removing BPS though.

I'm not including BPS anymore since 0.15 has blueprint storage capability. BPS soft mod also had bugs in it that caused crashes so I wanted to dump it as soon as 0.15 came out.

**Comment by Oarcinae** [comment]
Closing this as blueprints are vanilla now and scenario runs fine.
