### ISSUE TITLE
Crash - Join Another Spawn

### ISSUE THREAD

**Issue by ThoronadNg** [Oarcinae/FactorioScenarioMultiplayerSpawn#174]
### **Issue**  
When a spawn is about to be cleaned while sharing is enabled and another player has the "Spawn Options" menu open, the spawn remains selectable. If the spawn is selected just before the cleanup, the server crashes.

---

### **Steps to Reproduce:**

1. **Player 1** creates a new spawn.
2. **Player 1** enables spawn sharing.
3. **Player 2** opens the "Spawn Options" menu.
4. **Player 1's** spawn is cleaned up either by:
   - Admin action
   - Disconnecting before the minimum timer expires.
5. **Player 2** selects **Player 1's** spawn from the "Select Shared Spawn" dropdown (the spawn remains visible in the menu even after the cleanup process starts).
6. The server crashes.

---

### **Expected Behavior**  
The spawn should be removed from the "Spawn Options" menu as soon as it enters the cleanup state, preventing further selection and avoiding server crashes.

---

### **Actual Behavior**  
The spawn remains visible and selectable during cleanup, leading to a server crash if selected.

![grafik](https://github.com/user-attachments/assets/3fe2ca26-a355-439a-afcf-02820cea820a)

**Comment by Oarcinae** [comment]
@ThoronadNg Thanks for the report! Will look into this soon and will post back when I have a fix published.
