### ISSUE TITLE
Request: Reassign Players to Default Permissions After Spawn Selection

### ISSUE THREAD

**Issue by ThoronadNg** [Oarcinae/FactorioScenarioMultiplayerSpawn#175]
### **Issue**  
New players are initially assigned to a specific permissions group. However, after selecting a spawn, they are not reassigned back to the default group as expected.

### **Desired Behavior**  
I would like to configure specific permissions for the default group, such as disabling the ability to import blueprints.

**Comment by Oarcinae** [comment]
Thanks for the report! Yeah, this is my first time doing anything with permissions. I'll  look into it and come back to you if I have any questions. Otherwise, sounds easy to fix this.

**Comment by Oarcinae** [comment]
Apparently the default group has a capital D...
