### ISSUE TITLE
Scenario Template config.lua mentions config_mod.lua, which does not exist

### ISSUE THREAD

**Issue by bplein** [Oarcinae/FactorioScenarioMultiplayerSpawn#176]
I'm excited that OARC is a mod now, and am working on my automation for the small number of headless servers I run. 

I'd  like to modify many settings, but there's only a few examples in `config.lua` and the file itself says to look in `config_mod.lua` which does not exist. 

While I can try and interpret what these should be, is there a way we could get a fully populated example file?

**Comment by bplein** [comment]
I may have sort of answered my question, modifiable settings are in config_parser.lua

What I did to figure out syntax was to export settings from the OARC UI, reformatted them as if they were JSON, and then copy and pasted sections from there into control.lua, modifying with`modifiedsettings.` in front of them. It works!

Still, an example file would be helpful for people.

**Comment by Oarcinae** [comment]
Yeah, some of my file comments are out of date, specifically in config.lua. I need to update some older references, the correct way going forward is to make a copy of the example scenario, edit it as needed and use that to "init" the mod.

It sounds like you figured out the example scenario template though? Feel free to ping me in discord too and I can answer questions there as they come up.

**Comment by bplein** [comment]
Yes, I have it figured out. I'm good for now.

**Comment by Oarcinae** [comment]
@bplein I'll make a full template at some point, here's the issue for me to remind myself: https://github.com/Oarcinae/FactorioScenarioMultiplayerSpawn/issues/188

I want to automate it so I don't have to manually edit the template every time I update any of the settings, I just need to figure out a simple way to do that first.
