### ISSUE TITLE
Add option for multiple rocket silos

### ISSUE THREAD

**Issue by Oarcinae** [Oarcinae/FactorioScenarioMultiplayerSpawn#21]

**Comment by ErnestUTN** [comment]
This would be great for a PVP scenario.. I am currently trying to mod the code to make it a 1 vs 1 PVP. This is to say: Two rocket silo chunk generated with different locations and forces alignments, and hidden from enemy visuals. Each player has to travel to its silo. Place defenses and defend it .

First force to destroy the other's silo or launch his own wins.

**Comment by Oarcinae** [comment]
Added more Silos. I don't plan to support PvP.
