### ISSUE TITLE
Localization RUS (Done)

### ISSUE THREAD

**Issue by KORESHon** [Oarcinae/FactorioScenarioMultiplayerSpawn#259]
Лишних слов не надо, вот [ru.zip](https://github.com/user-attachments/files/17788200/ru.zip)
закинуть просто в oarcmod/locale

UPD: Перевод может быть кривым, т.к. переводил с помощью ИИ (deepl). Но он легко чинится.

**Comment by Oarcinae** [comment]
Thanks, I'll add it when I do the next release.
