### ISSUE TITLE
Feature Request: See Player Names and Color via Map rather then red enemy dot.

### ISSUE THREAD

**Issue by KaneHart** [Oarcinae/FactorioScenarioMultiplayerSpawn#26]
Not sure if this is possible via the API and if not maybe we can put a request in since there is more chance of it getting added in 0.15.

But I like to see peoples name / color rather then just a red dot.

With shared vision it's not too bad but once I place tons and tons of radars, etc it's almost impossible to find them via the map. I experienced this a lot in 0.15.

**Comment by Oarcinae** [comment]
Yeah I don't think I can do anything about that unfortunately. But I know exactly what you mean.
If I think of something, I'll try it out, but I don't know of a way to do text over the map yet.

**Comment by KaneHart** [comment]
Ahh not a problem. Was just an idea. I love to see more just random co-op features in the game overall :) We just started playing and having a blast. I did a lot of editing overall though for our game but that is the nice part of configs.

Going to close this :)
