### ISSUE TITLE
Scenario crashes on initial load

### ISSUE THREAD

**Issue by jar349** [Oarcinae/FactorioScenarioMultiplayerSpawn#29]
[Screenshot](http://imgur.com/a/rggIJ) of the error.

Game is: 0.14.23.
Grabbed the locale zip and the scenario zip from the master branch of each.

After installing:
1. Multiplayer
2. Custom Scenario
3. FactorioScenarioMultiplayerSpawn
4. Load

**Comment by Oarcinae** [comment]
Yeah, I updated a lot of stuff to be compatible with 0.15.X

I'll make a note that only 0.15 is supported at this time. If you want to, you can browse the previous commits to get a working version for 0.14

**Comment by jar349** [comment]
Would you please consider finding the correct commit and adding a 'git tag v0.14.x'?

**Comment by Oarcinae** [comment]
Will do when I get time.
