### ISSUE TITLE
If regrowth is disabled, server crashes on early player exit

### ISSUE THREAD

**Issue by sapid** [Oarcinae/FactorioScenarioMultiplayerSpawn#32]
If regrowth is disabled and a player leaves in their first five minutes after creating a new base, separate_spawns.lua will try to mark their base for regrowth cleanup and crash immediately due to referencing a nil index.

**Comment by Oarcinae** [comment]
Excellent find, as you can tell, I didn't do much testing with disabling some options in this latest release. I'll add in the fix. Thanks!

**Comment by zackbcom** [comment]
I would love to see this added in. Server is crashing with regrowth disabled. Thanks!
