### ISSUE TITLE
Add interactive request with approval from spawn host when players request to join.

### ISSUE THREAD

**Issue by Oarcinae** [Oarcinae/FactorioScenarioMultiplayerSpawn#42]
Add interactive request with approval from spawn host when players request to join.

Possible flow:
1. Player 1 starts a new base.
2. Player 1 opens up base for requests.
3. Player 2 joins game and requests to join.
4. Player 1 has to open up spawn control menu to view new requests, can click on buttons with player name to allow them in.
5. If allowed, player 2 joins. If not allowed, player 2 can opt to cancel request and go back to spawn menu.

Menu navigation will be tricky to make sure there are no edge cases.

**Comment by AusKarlos** [comment]
Add a double confirmation to reduce edge case.
5. Player opens up spawn control menu to view pending requests, clicks on accept or reject button with players name next to the GUI buttons to allow / reject.
6. If allowed player 2 gets a popup GUI message to click to join, If rejected player 2 is notified and returns to lobby menu.

**Comment by Oarcinae** [comment]
Added in a basic GUI system to allow/deny. No fancy auto-timeout stuff yet and it's likely a bit buggy around edge cases. Any help testing this would be greatly appreciated.

**Comment by Oarcinae** [comment]
Marking this one as done.
