### ISSUE TITLE
Persistent can_scroll_horizontally error

### ISSUE THREAD

**Issue by Cyberzoid1** [Oarcinae/FactorioScenarioMultiplayerSpawn#45]
I am getting the horizontal scroll error on our server since 0.16.16 update.

>   49.281 Error MainLoop.cpp:1013: Exception at tick 13397282: Error while running event level::on_gui_click (ID 1)
LuaGuiElement doesn't contain key can_scroll_horizontally.
stack traceback:
	/opt/factorio/temp/currently-playing/locale/oarc_utils.lua:548: in function 'ExpandPlayerListGui'
	/opt/factorio/temp/currently-playing/locale/oarc_utils.lua:569: in function 'PlayerListGuiClick'
	/opt/factorio/temp/currently-playing/control.lua:175: in function </opt/factorio/temp/currently-playing/control.lua:169>
  49.282 Error ServerMultiplayerManager.cpp:95: MultiplayerManager failed: "Error while running event level::on_gui_click (ID 1)
LuaGuiElement doesn't contain key can_scroll_horizontally.
stack traceback:
	/opt/factorio/temp/currently-playing/locale/oarc_utils.lua:548: in function 'ExpandPlayerListGui'
	/opt/factorio/temp/currently-playing/locale/oarc_utils.lua:569: in function 'PlayerListGuiClick'
	/opt/factorio/temp/currently-playing/control.lua:175: in function </opt/factorio/temp/currently-playing/control.lua:169>"

This was fixed in 49e2a79bab40ef19404f1d224329d3f4aa33a8ee however I am still getting the error in the map save.

I backed up the world and created a new map to test that the scenario was indeed working after your update and found it was fixed for a new world.

Is there a way to correct the change in the original map save?

**Comment by Oarcinae** [comment]
You could try opening up the save file and editing the scenario in it. The save file is just a zip and I believe it contains the scenario lua as well. No guarantees if that will work or just break it completely.

**Comment by Cyberzoid1** [comment]
Tried that :)
control.lua doesnt have anything related
And I cant find a way to open/read the .dat files
No scenario references
[world.zip](https://github.com/Oarcinae/FactorioScenarioMultiplayerSpawn/files/1628781/world.zip)

For your scenario, or scenarios in general, are the scripts copped to the world safe or are they referenced externally in the scenario files.  Since I've updated the scenario this doesn't seem like it reads from the scenario once the map has been created.

**Comment by Oarcinae** [comment]
That's weird... this is the save for my scenario that I'm running right now: 
![image](https://user-images.githubusercontent.com/23324249/34910727-6342c16e-f889-11e7-952b-20658672d802.png)

I was expecting that if you were running my scenario, it should look like that. However, maybe the upgrade between different versions breaks the save? No idea though. You should be able to edit "separate_spawns_guis.lua" if you can see it in the save though...

**Comment by Cyberzoid1** [comment]
derp! Apparently I was looking inside the wrong wold save. Thanks for hinting at that.
Made the changes from 49e2a79bab40ef19404f1d224329d3f4aa33a8ee into the world save and now it seems to be working again.
Thanks
