### ISSUE TITLE
Can not rejoin server

### ISSUE THREAD

**Issue by NanoPirate** [Oarcinae/FactorioScenarioMultiplayerSpawn#48]
just created a new headless server on my local machine and got it working propperly.
after installing this mod the server and all mod features worked but people are unable to rejoin the server, getting following error message:

          "Cannot join. The following mod script files are not identical between you and the server: level"

am i doing something wrong or is the mod broken?

**Comment by Oarcinae** [comment]
Well, this isn't a mod, it's a scenario. So that error is unrelated to this scenario most likely..

You should be able to look at the mod list in the server and see if it matches your own?

**Comment by NanoPirate** [comment]
the server has no mods, but this issue might been caused by me playing from the same machine i hosted from. i got me a new server and trying to set it all up there

**Comment by NanoPirate** [comment]
ok creating the server on another machine solved the issue, sorry for inconvenience!

**Comment by Oarcinae** [comment]
Weird, thanks for reporting your findings! Glad you fixed it :)
