### ISSUE TITLE
Server Crash when not using RSO

### ISSUE THREAD

**Issue by xkuyax** [Oarcinae/FactorioScenarioMultiplayerSpawn#49]
Hi, 
when you disable RSO in the config.lua and you generate a spawn far away the game/server crashes 

2018-10-14 12:05:04 [JOIN] xkuyax joined the game
  34.702 Error MainLoop.cpp:1035: Exception at tick 1141: Error while running event level::on_tick (ID 0)
...10/factorio/temp/currently-playing/locale/oarc_utils.lua:1091: attempt to index local 'surface' (a nil value)
  34.702 Error ServerMultiplayerManager.cpp:96: MultiplayerManager failed: "Error while running event level::on_tick (ID 0)
...10/factorio/temp/currently-playing/locale/oarc_utils.lua:1091: attempt to index local 'surface' (a nil value)"

Configuration: https://hastebin.com/tiduholuta.makefile

**Comment by Oarcinae** [comment]
Hmm, thanks for reporting. I'll try looking into it. Were you running with any other mods? Latest version I'm assuming?

**Comment by xkuyax** [comment]
Yeah latest factorio version and no other mods

**Comment by Oarcinae** [comment]
@xkuyax Looks like a simple bug to fix. I just pushed a change, can you check if that fixes it for you?

**Comment by Oarcinae** [comment]
Closing this since I didn't hear back and no other complaints.
