### ISSUE TITLE
Convert separate spawns into a mod?

### ISSUE THREAD

**Issue by Oarcinae** [Oarcinae/FactorioScenarioMultiplayerSpawn#5]
Wild idea, but would be nice to create a mod that is at least compatible with something like RSO...
I haven't done any actual mods before.

**Comment by petrukhnov** [comment]
Yes, that would be great! Also if it could work with new ores.

**Comment by JamieKG** [comment]
Did you ever do this @Oarcinae a mod for just separate spawns also the buddy or new team option would be great using something like https://mods.factorio.com/mod/diplomacy for a pvp element

**Comment by Oarcinae** [comment]
Unfortunately no... I wrote the scenario code in a very bad way so it will be hard to convert to a mod that is compatible with other mods.

**Comment by DRY411S** [comment]
Yeah. In my mind, a mod is something that lets people change the way they play vanilla. A scenario like this is a different way to play.

It's not mod material.

**Comment by Oarcinae** [comment]
Someone did turn my scenario into a mod, but I'm having trouble finding a link right now. It was on the mod portal. It didn't have all my latest changes in it but it was in mod form. I never tried it out though.

**Comment by Oarcinae** [comment]
https://mods.factorio.com/mod/oarc-mod

Done, but will need work to polish it in mod form and make both versions compatible with each other as much as possible.
