### ISSUE TITLE
0.17 - "desert" is not a valid autoplace control name.

### ISSUE THREAD

**Issue by Canule** [Oarcinae/FactorioScenarioMultiplayerSpawn#55]
After upgrading 0.16 > 0.17
Hosting new scenario game.

>The scenario level caused a non-recoverable error.
>Please report this error to the scenario author.

> Error while running event level::on_init()
> "desert" is not a valid autoplace control name.
> stack traceback:
> 	...n/.factorio/temp/currently-playing/locale/oarc_utils.lua:1210: in function 'CreateGameSurface'
> 	/home/unr/.factorio/temp/currently-playing/control.lua:103: in function </home/unr/.factorio/temp/currently-playing/control.lua:91>
> stack traceback:
> 	[C]: in function 'create_surface'
> 	...n/.factorio/temp/currently-playing/locale/oarc_utils.lua:1210: in function 'CreateGameSurface'
> 	/home/unr/.factorio/temp/currently-playing/control.lua:103: in function </home/unr/.factorio/temp/currently-playing/control.lua:91>

**Comment by Oarcinae** [comment]
lol damn dude... 0.17 just dropped, give me a few days (possibly a week or 2) to get to updating haha.

But thank you! Now I know 0.17 is out :)

<3

**Comment by Canule** [comment]
no stress, just mentioning... :)

**Comment by bplein** [comment]
Thanks for maintaining this scenario! I'm a big fan of it.  There's other things like autofill (trains) and initial load out for new players that are broken as well, but I'm sure you are on it! Would you like me to open issues on each item as I find them? Or just wait for your 0.17-dev to drop and open new issues on that?

**Comment by Oarcinae** [comment]
No worries, I should be able to work on it this weekend I'm hoping. Pretty slammed at work right now.

For now, there probably isn't much point opening issues for each item as I'll be rewriting a ton of stuff and stripping out a bunch of old features/code.

If you can, just wait for the 0.17-dev and then I would love any help on debugging at that point.

For those who can't wait, I have a feeling the other so called "Oarc"-based scenarios that have been derived from mine will likely be updated faster. Take a look at the public forks from mine and keep an eye out there too. A lot of great modders have done their own versions of the scenario as well.

**Comment by bplein** [comment]
The public forks are all older than yours :) by the way. I'm sure there are some being maintained non-publicly. Anyhow, no rush, gotta fly out on a business trip today and need to sit and do taxes on Sunday.

**Comment by Oarcinae** [comment]
@bplein @Canule I created a dev_0.17 branch. It now runs and doesn't throw errors immediately. There is a lot missing (all soft-mods disabled, all extra options/features disabled), but the core game is playable I think. I have NOT tested multiplayer yet though, so that will be next.

Feel free to give it a try, just don't expect it to be pretty.

**Comment by Oarcinae** [comment]
Closing this since I've had several people run successfully. Open new tickets for each .17 bug found.
