### ISSUE TITLE
scenario2map breaks on oarc_gui_utils.lua

### ISSUE THREAD

**Issue by bplein** [Oarcinae/FactorioScenarioMultiplayerSpawn#57]
When using scenario2map to create a map, it errors out because the "require" line for oarc_gui_utils includes .lua extension, should be just oarc_gui_utils.

**Comment by bplein** [comment]
Sorry, should have said dev_0.17 branch

**Comment by bplein** [comment]
Doesn't seem to affect creating a game from scenario in the client, only on headless server using the scenario2map start function. 

My workaround for the moment is to create the maps on my desktop and load them to the server rather than create them on the server.

**Comment by Oarcinae** [comment]
Thanks for catching that! Odd that it only broke on scenario2map.
I'll get this in the next update for sure.

Also, what's the reason you use scenario2map? Just curious on the use case.

**Comment by bplein** [comment]
I run 3 headless servers. With scenario2map I can stop the server, create a new map based on a specific scenario, and restart the server. So no uploading of maps from desktop to server. I can also automate this for time-based reset although I’m not doing that yet. 

The servers all run in containers but that is just an implementation detail.

**Comment by bplein** [comment]
Also scenario2map worked great with 0.16

**Comment by Oarcinae** [comment]
Hmmm, you don't or can't use --start-server-load-scenario instead?

**Comment by bplein** [comment]
It has to do with the way you use a container. If my container launch used that command, every time it restarted it would wipe the map. 

I ~could~ start it that way and then wait some time and then issue a save via RCON and then wait until I think the save is complete and then kill the container and then restart it with the normal command. See how convoluted that is?  Just using a supported command designed to do what I want which is to launch the scenario and save and exit.

**Comment by Oarcinae** [comment]
Thanks for explaining your process, I'm always interested in learning different methods like that. I don't use containers at the moment but I could understand that being a problem.

I don't normally test scenario2map so let me know if you find anything else like that.

I'm assuming just changing the require to drop the .lua extension (which shouldn't have been there anyways) fixed it? I'll close this issue then since I added that in. Let me know if that's not the case or if I missed anything else.

**Comment by bplein** [comment]
I’ll test the syntax change between containers and desktop and leave feedback here but yes let’s close it for now.

**Comment by Oarcinae** [comment]
@bplein Do you use --map-gen-settings and/or --map-settings with scenario2map? I can't tell if that is supported or not.

**Comment by bplein** [comment]
I haven't. In fact, I haven't generated a new map in a month since you updated the code for 0.17 (I haven't picked up any new code since then either)
