### ISSUE TITLE
0.17 Alien issues 

### ISSUE THREAD

**Issue by IIPoliII** [Oarcinae/FactorioScenarioMultiplayerSpawn#59]
I have founded out aliens are having troubles since 0.17 we have these kind of cases on the server since the 0.17 and it's way too much to kill them for now any ideas how to fix it?
![Aliens](https://cdn.discordapp.com/attachments/420865611279630338/551858409121513483/unknown.png)

**Comment by Oarcinae** [comment]
Did you modify the vanilla map generation settings? You will need to change the default resource/map generation settings to fix this.

How are you launching the server?

This is my recommendation if you can do it, either launch via OPTION 3 (see the README) and make sure to specify map-gen-settings. I have just added an example config to this dev branch for you to copy, I tested it at far distances and it looked reasonable.

OR if you are generating using OPTION 1 or 2, make sure to set frequency very low for all resources and enemies, richness lower, and size probably default is fine.


These are my current resource/enemy settings:
`"autoplace_controls" : {
        "coal"        : {"frequency" : 0.20, "richness" : 0.50, "size" : 1.50},
        "copper-ore"  : {"frequency" : 0.20, "richness" : 0.50, "size" : 1.50},
        "crude-oil"   : {"frequency" : 0.20, "richness" : 0.50, "size" : 1.50},
        "enemy-base"  : {"frequency" : 0.20, "richness" : 0.50, "size" : 0.50},
        "iron-ore"    : {"frequency" : 0.20, "richness" : 0.50, "size" : 1.50},
        "stone"       : {"frequency" : 0.20, "richness" : 0.50, "size" : 1.50},
        "trees"       : {"frequency" : 0.50, "richness" : 1.00, "size" : 1.50},
        "uranium-ore" : {"frequency" : 0.20, "richness" : 0.50, "size" : 1.50}
    }
`

**Comment by IIPoliII** [comment]
Thanks for your help fixed it i think !

**Comment by IIPoliII** [comment]
Hello, i have founded out i finnaly still have the issue by trying with the map-settigns AND the map-gen-settigns. Sadly i still spawn with tons of aliens around. 
![image](https://user-images.githubusercontent.com/29628512/54314466-075a7080-45dc-11e9-9cac-628917c8291e.png)

I am trying to fix it but i can't :/

**Comment by IIPoliII** [comment]
Said nothing didn't saw you did an update thanks for your awesome work c:

**Comment by Oarcinae** [comment]
@IIPoliII Let me know how the new enemy tweaking works. I tried to scale it better so that everything isn't behemoth worms everywhere lol...

**Comment by IIPoliII** [comment]
Well it works pretty well but I touched control or config.lua a bit I don't know which one too but I made everything x4 wait I show you the file 2 sec

**Comment by IIPoliII** [comment]
```
-- Safe area has no aliens

-- +/- this in x and y direction

SAFE_AREA_TILE_DIST = CHUNK_SIZE*20

-- Warning area has significantly reduced aliens

-- +/- this in x and y direction

WARNING_AREA_TILE_DIST = CHUNK_SIZE*40

-- 1 : X (spawners alive : spawners destroyed) in this area

WARN_AREA_REDUCTION_RATIO = 80

-- Danger area has slightly reduce aliens

REDUCED_DANGER_AREA_TILE_DIST = CHUNK_SIZE*120

-- 1 : X (spawners alive : spawners destroyed) in this area

REDUCED_DANGER_AREA_REDUCTION_RATIO = 20


```
This is a bit too much like I would remove 25% and was a really good setting

**Comment by IIPoliII** [comment]
What I mean with the 25% is that instead of 20 having like 15 and it would be good I think

**Comment by Oarcinae** [comment]
@IIPoliII What map-gen-settings are you using? Specifically, what is your enemy settings?
Is it similar to this: `"enemy-base"  : {"frequency" : 0.20, "richness" : 0.50, "size" : 0.50},` ?

40 and 120 chunk radius is pretty huge :)

**Comment by IIPoliII** [comment]
I think it's these ones normally but I think maybe I will put less margin because yeah it's huge but the margin you putted in the base script was to tiny for me because some bases where already pretty big near the main base. For now I am trying the settings once I have got the perfect one if you want I can post it I will probably try tommorow c:

**Comment by Oarcinae** [comment]
![image](https://user-images.githubusercontent.com/23324249/54324418-08879f80-45d4-11e9-98ce-e05b7caa5c96.png)


This is kind of what you should see with my current default settings. The close by enemies are all very easy to clear, small worms, very few bases. You won't see any huge/behemoth worms until you are at the huge bases at the edges of the screenshot. It should be close to the vanilla experience.

**Comment by IIPoliII** [comment]
I see, is intressting but i found for favouriting rail world i prefer letting more margin at the end i putted 
```
---------------------------------------
-- Safe Spawn Area Options
---------------------------------------

-- Safe area has no aliens
-- +/- this in x and y direction
SAFE_AREA_TILE_DIST = CHUNK_SIZE*15

-- Warning area has significantly reduced aliens
-- +/- this in x and y direction
WARNING_AREA_TILE_DIST = CHUNK_SIZE*30

-- 1 : X (spawners alive : spawners destroyed) in this area
WARN_AREA_REDUCTION_RATIO = 60

-- Danger area has slightly reduce aliens
REDUCED_DANGER_AREA_TILE_DIST = CHUNK_SIZE*90

-- 1 : X (spawners alive : spawners destroyed) in this area
REDUCED_DANGER_AREA_REDUCTION_RATIO = 15
```

**Comment by Oarcinae** [comment]
That looks good, if I'm not mistaken, default train world uses `{"frequency" : 1.00, "richness" : 1.00, "size" : 0.50}` or something like that, so there are actually still a lot of enemies.

I'll probably tweak my numbers up a bit to be closer to yours. Thanks for reporting your findings!

**Comment by IIPoliII** [comment]
Maybe you should at least now the issues i see is that even with this seettings i would better make a huger safe area since abandoned bases > than 15 minutes get a lot of notifications and it's annyoing

**Comment by Oarcinae** [comment]
Done, I tweaked it up a bit, not all the way to yours but closer. Maybe I can expose a "Delete Base" admin option for deleting abandoned bases / players or something to help with that issue.

Also, I change how the config.lua resources are done based on other requests and suggestions, let me know what you think.

**Comment by IIPoliII** [comment]
Yes sure will be availbe in my next map reset c: ! The idea of base removal would be a really great freature. And the thing who often happen is this 
![image](https://user-images.githubusercontent.com/29628512/54462309-93e96800-476f-11e9-9742-21127a4bbcd7.png)
And even with my safe zone pretty big it's werid. maybe i wrote it wrong xD ?
But what is annoying is the song because you don't even really know about it. And i saw if there is no radar the base don't get attacked?

**Comment by IIPoliII** [comment]
Maybe can i ask you if you have discord wouldn't it be easier to found out the perfect settigns and freatures who could be nice or unusefuel c:

**Comment by Oarcinae** [comment]
Add me Oarc#8695
