### ISSUE TITLE
Add support for RSO mod.

### ISSUE THREAD

**Issue by Oarcinae** [Oarcinae/FactorioScenarioMultiplayerSpawn#61]
I suspect RSO will break my spawns by allowing enemies to be very close to spawn points, if not right on top of. Will need some kind of delay mechanism and checks in place.

**Comment by Rsslone** [comment]
Can confirm that it does break spawns. Here is what a Far spawn looks like with RSO and safe zone of *30

 https://i.imgur.com/KehgN59.png

**Comment by Rsslone** [comment]
A easy work around is to disable RSO biter generation. Then the safe spawns work correctly.

**Comment by Oarcinae** [comment]
@Rsslone Thank you for the confirmation and image! And the workaround! Very much appreciated.

Regarding the work around, as long as you also tweak the vanilla enemy settings (freq / size / rich), it should end up being pretty playable.

Let me know if you see any other issues. I'll keep this open until I find a good solution (delayed function for clearing enemies, most likely).

**Comment by Rsslone** [comment]
No problem. I'll comment further as I get more play time in, as of my initial testing the workaround works great. The bigger issue is with ores, there is a chance to spawn on top of an already existing patch, and in turn you'll have overlapping patches. I'm not sure if you already have checks for that but just not the ores I am using. (Angels Ores)

**Comment by Oarcinae** [comment]
I'm on the fence about this one due to the complexity of adding checks and support for the RSO resource generation. I suspect converting the scenario to a mod, and settings RSO as a dependency MAY solve some of these issues but I have a while to go before I can verify this.

**Comment by Oarcinae** [comment]
I'm going to mark this as won't do... it's been over a year. I (and the players I host) are happy without RSO so I don't think it's a requirement anymore like it used to be.
