### ISSUE TITLE
Restart is hard to hover-over

### ISSUE THREAD

**Issue by davv1** [Oarcinae/FactorioScenarioMultiplayerSpawn#65]
As you can see, I can click ban without problems:

![obraz](https://user-images.githubusercontent.com/13569795/54472217-4d265d00-47c5-11e9-830b-8a20f296b50f.png)

But I can't click restart so easily:

![obraz](https://user-images.githubusercontent.com/13569795/54472225-5b747900-47c5-11e9-88be-1931f5d090a0.png)

Related with new change in #50

**Comment by davv1** [comment]
Here's GIF version with cursor which is possible to see.

https://i.imgur.com/miCn1wN.gifv

**Comment by Oarcinae** [comment]
Hmm, I can't reproduce this issue. When I launch my game the hover color always works.

I suspect this is either a conflict with the other mod GUIs you have, or maybe a bug in the game itself. I tested with both full screen and windowed.

**Comment by Oarcinae** [comment]
@davv1 I'll probably close this issue soon if I can't reproduce it since I think it's not the fault of my scenario code but something else.

**Comment by davv1** [comment]
Ok, go on. If someone will find similar issue then he/she will open new report, it's not issue which makes restart unclickable so we can go on for sure ;)
