### ISSUE TITLE
0.17 Crash log Scenario

### ISSUE THREAD

**Issue by IIPoliII** [Oarcinae/FactorioScenarioMultiplayerSpawn#66]
Heya! Have founded a new crash just a few minutes ago here is the log 
```
58899.507 Info ServerMultiplayerManager.cpp:922: Disconnect notification for peer (40)
58899.507 Info ServerMultiplayerManager.cpp:813: updateTick(5324135) received stateChanged peerID(40) oldState(InGame) newState(DisconnectScheduled)
58899.562 Error MainLoop.cpp:1128: Exception at tick 5324135: The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_player_left_game (ID 44)
/home/fctrserver/temp/currently-playing/lib/oarc_utils.lua:625: attempt to get length of local 'inv' (a nil value)
stack traceback:
        /home/fctrserver/temp/currently-playing/lib/oarc_utils.lua:625: in function 'DropGravestoneChests'
        ...ctrserver/temp/currently-playing/lib/separate_spawns.lua:56: in function 'FindUnusedSpawns'
        /home/fctrserver/temp/currently-playing/control.lua:210: in function </home/fctrserver/temp/currently-playing/control.lua:208
58899.570 Error ServerMultiplayerManager.cpp:92: MultiplayerManager failed: "The scenario level caused a non-recoverable error.
Please report this error to the scenario author.

Error while running event level::on_player_left_game (ID 44)
/home/fctrserver/temp/currently-playing/lib/oarc_utils.lua:625: attempt to get length of local 'inv' (a nil value)
stack traceback:
        /home/fctrserver/temp/currently-playing/lib/oarc_utils.lua:625: in function 'DropGravestoneChests'
        ...ctrserver/temp/currently-playing/lib/separate_spawns.lua:56: in function 'FindUnusedSpawns'
        /home/fctrserver/temp/currently-playing/control.lua:210: in function </home/fctrserver/temp/currently-playing/control.lua:208>
58899.570 Info ServerMultiplayerManager.cpp:714: updateTick(5324135) changing state from(InGame) to(Failed)
58899.570 Quitting: multiplayer error.
58899.570 Info GlobalContext.cpp:686: Waiting for child processes to exit:
58900.380 Info ServerMultiplayerManager.cpp:138: Quitting multiplayer connection.
58900.380 Info ServerMultiplayerManager.cpp:714: updateTick(4294967295) changing state from(Failed) to(Closed)
58900.381 Info HttpSharedState.cpp:54: Downloading https://multiplayer.factorio.com/remove-game/4707149
58900.479 Info UDPSocket.cpp:210: Closing socket
58900.479 Info UDPSocket.cpp:240: Socket closed
58900.479 Info UDPSocket.cpp:210: Closing socket
58900.552 Info UDPSocket.cpp:210: Closing socket
58900.552 Info UDPSocket.cpp:240: Socket closed
58900.553 Goodbye


```

**Comment by Oarcinae** [comment]
That's an odd error... that piece of code has been untouched for a long time now. Are you using any mods that modify inventory of the player or anything like that?

Also, I forgot that I wanted to remove the gravestone mod. I already removed other parts of it, like the enable/disable option in config.lua

I don't have a very good implementation for gravestone, it's probably better handled by an actual mod instead of my shitty soft mod.

I can add in a check to try and stop it happening again, or I could just remove it since I had planned on removing it anyways. let me know if you have strong feelings one way or another.

**Comment by Oarcinae** [comment]
I went ahead and just removed it for now. The gravestone dropping for players leaving early was mostly to stop griefing but I don't really care about that.

**Comment by IIPoliII** [comment]
Oh do you know if it's correctible how does it prevents greiffing? C: I would be still interested about this softmod I know Mods could be used I tried Mods once even with the 0.17 most people's don't join

**Comment by Oarcinae** [comment]
The idea is that if someone joins a game, picks up a bunch of expensive stuff, and then leaves within a short time, all the items are dumped into a chest so they don't disappear when the player leaves.

But it's very rare that this is abused, and I think it's better just to ban people instead.

This specific piece of code was left over in a place that I had forgotten about. I'm not sure it even had any real use to be honest.

**Comment by IIPoliII** [comment]
Oh I see yeah then it has no real use its rare they spawn directly in main base too
