### ISSUE TITLE
0.17 - always spawn in water

### ISSUE THREAD

**Issue by BurtGummer** [Oarcinae/FactorioScenarioMultiplayerSpawn#67]
Hello,

first, thank you VERY VERY much for this great mod! Without, a MP-Server is not really good.

Now the problem, i try some options in the `../data/map-gen-settings.json` and the `../scenarios/FactorioScenarioMultiplayerSpawn/config.lua` nad now, always i create a new map with:

`/home/factest/factorio/bin/x64/factorio --start-server-load-scenario FactorioScenarioMultiplayerSpawn --map-gen-settings /home/factest/factorio/data/map-gen-settings.json --server-settings /home/factorio/factorio/data/server-settings.json`

I spawn "Far" in the water:

![grafik](https://user-images.githubusercontent.com/1249295/54561313-a27c8d00-49c4-11e9-9aa1-b2941cda03cd.png)

This are the parts i have changed from config.lua:
```

{
  "_terrain_segmentation_comment": "Inverse of map scale",
  "terrain_segmentation": 1,

  "_water_comment":
  [
    "Multiplier for water 'coverage' - higher increases the water level.",
    "Water level = 10 * log2(this value)"
  ],
  "water": 1,

  "_comment_width+height": "Width and height of map, in tiles; 0 means infinite",
  "width": 0,
  "height": 0,

  "_starting_area_comment": "Multiplier for 'biter free zone radius'",
  "starting_area": 1,

  "peaceful_mode": false,

  "autoplace_controls":
  {
    "coal": {"frequency": 2, "size": 2, "richness": 2},
    "stone": {"frequency": 2, "size": 2, "richness": 2},
    "copper-ore": {"frequency": 2, "size": 2,"richness": 2},
    "iron-ore": {"frequency": 2, "size": 2, "richness": 2},
    "uranium-ore": {"frequency": 2, "size": 2, "richness": 2},
    "crude-oil": {"frequency": 2, "size": 2, "richness": 2},
    "trees": {"frequency": 3, "size": 6, "richness": 6},
    "enemy-base": {"frequency": 1, "size": 1, "richness": 1}
  },

```

Any ideas?

**Comment by Oarcinae** [comment]
Hmmm,

Are you saying that you always spawn in the water or just sometimes? **My mod does not avoid water spawns**, it is possible you just spawned in a large lake.

Did you try to map the area around? `/c game.player.force.chart(game.player.surface,{{x = game.player.position.x-500, y = game.player.position.y-500}, {x = game.player.position.x+500, y = game.player.position.y+500}})`

**Comment by Oarcinae** [comment]
Ohhhhhh... you copied directly from map-gen-settings.example.json didn't you?

```
  
  "_property_expression_names_comment":
  [
    "Overrides for property value generators",
    "Elevation influences water and cliff placement.",
    "Leave it blank to get 'normal' terrain.",
    "Use '0_16-elevation' to reproduce terrain from 0.16.",
    "Use '0_17-island' to get an island."
  ],
  "property_expression_names":
  {
    "elevation": "0_17-island",
    
    "control-setting:aux:bias": "0.300000",
    "control-setting:aux:frequency:multiplier": "1.333333",
    "control-setting:moisture:bias": "0.100000",
    "control-setting:moisture:frequency:multiplier": "0.500000"
  },
```

REMOVE the "elevation" or the whole section if you don't want it. This causes "island" map type.

**Comment by BurtGummer** [comment]
Yes, thank you very much! I have delete the line `"elevation": "0_17-island",` and now I spawn in the wood, great!
