### ISSUE TITLE
(0.17) Some questions

### ISSUE THREAD

**Issue by BurtGummer** [Oarcinae/FactorioScenarioMultiplayerSpawn#68]
Hello,

i play some days with this scenario. I try to setup a cool multiplayer server for family and friends.

One question is, if i spawn solo, can i change the team later?
Can more than 2 player join a team?
Can i move from the "main group" to my own group, if i first select the main team? 
Oarcinae, where are you from? I like to spend you a beer! ;-)

Burt

**Comment by Oarcinae** [comment]
Hi!

I'm glad you're enjoying the scenario!

1. If you choose "Create Your Own Team". There is no easy way to change teams later. However, if you are willing to try you can use this command: `/c MergeForcesKeepResearch(game.players["player1"].force, game.players["player2"].force)`. This will make "player2" join "player1"'s force but it will keep ALL research that both teams have done. All buildings of player2 will become part of player1's team as well I think.
![image](https://user-images.githubusercontent.com/23324249/54622423-f5dff100-4a3f-11e9-8299-85f63a30243d.png)


2. Yes, if someone "shares" their base you can try this:
![image](https://user-images.githubusercontent.com/23324249/54622063-39862b00-4a3f-11e9-8d52-bc56199ecc80.png)
![image](https://user-images.githubusercontent.com/23324249/54622086-4acf3780-4a3f-11e9-9c76-2ff6a199ec3c.png)
![image](https://user-images.githubusercontent.com/23324249/54622104-53c00900-4a3f-11e9-8284-db68d739a443.png)

3. Unfortunately it's a bit hard to change to a NEW team. I think you would have to use a command like this `/c game.player.force=game.create_force("new_force_name")`. But I don't know if this will work at all... Good luck :)

4. Haha thanks, I'm in the US right now. Don't worry about sending me anything, just let me know when you find any bugs or problems with the scenario that I can fix. I'll have a beer to celebrate :)

**Comment by BurtGummer** [comment]
Great, thank you very much for your answers! :-)

**Comment by Oarcinae** [comment]
Feel free to ask any more questions if you have them. You can always reach me on discord as well: Oarc#8695
