### ISSUE TITLE
Anti-Griefing config settings duplicated in example.

### ISSUE THREAD

**Issue by CaspianDrago** [Oarcinae/FactorioScenarioMultiplayerSpawn#75]
Example-config.lua lines 425-435 can be removed as duplicate.  It is currently set on lines 377-387.  

in Dev 0.17 branch.

**Comment by Oarcinae** [comment]
Ty, will remove dupes!

Also, please let me know if you see any desync with the latest changes. I'm worried I broke something, I tried to host a server last night with the new vanilla spawns and it kept desyncing me where I was testing leaving and joining before the leave time limit.
