### ISSUE TITLE
idea: send a gift to a player

### ISSUE THREAD

**Issue by BurtGummer** [Oarcinae/FactorioScenarioMultiplayerSpawn#78]
Hello,

is there a way, to send a player a gift, for example, a weapon with ammo?

**Comment by Oarcinae** [comment]
You'd just have to use the command line directly for something like that.
/c game.players["player_name"].insert(item)

Item would be something like {name="pistol", count=1} or {name="firearm-magazine", count=100}
You have to look up all the items to figure out which ones you want..

**Comment by davv1** [comment]
You can also just come to him and use Ctrl+Click, but that requires coming to them.
