### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by leoycx** [Oarcinae/FactorioScenarioMultiplayerSpawn#9]
please 

- add some admin tool

it better to edit default settings
- reduce re spawn cool down time to 15min
- start res change to 5000

**Comment by Oarcinae** [comment]
What would you like in the admin tools? How would they work exactly?

Yeah I can change the respawn cooldown since I don't think it's a very OP power anyways.
I'm happy with the current resource balance and it's easy enough to change in the config file for anyone who wants to host/change it.

**Comment by Oarcinae** [comment]
Closing since it's not clear what should be in the admin tool. Default settings can be changed by anyone and are personal preferences.
