### ISSUE TITLE
dev_0.17 - Question about resource patch locations

### ISSUE THREAD

**Issue by bplein** [Oarcinae/FactorioScenarioMultiplayerSpawn#90]
This is more of a question than a bug!

I have been a long time user of OARC and in the latest dev_0.17 the resource locations (offsets) don't line up with the older settings from the 0.15 days. 

In other words, if I take the X and Y offsets and sizes I used for the older versions, and put them in config.lua, the patches are in different areas.

My guess is that the old system used one origin for each patch and the new system uses a different origin (i.e. maybe the old system was top-left origin while the new system is centered). 

In any event, I can try and reverse engineer it, but if you could describe the differences, I could figure out how to change my settings without saving and retrying a thousand times (grin).

Thanks again, I love this scenario!

**Comment by Oarcinae** [comment]
Hmm to be honest I've made so many changes along the way I don't know what the steps are to get what you are asking for. If it makes you feel any better I don't see any planned changes in the future for resource spawning.

What is your desired layout of resources like?

**Comment by bplein** [comment]
Oh, it's no big deal. I was using square patches (which is easy enough on your system) set in specific locations (big copper to the left, big iron to the right, coal above the copper, stone and uranium above the iron). If I plug those in, they overlap. So I'm thinking your new system places the patch around the coordinates give, while the old system placed, say, the upper left corner. So I just need to figure out how it's different and adjust.

OR, like I'm doing now, is use your radian-based placement with round patches and let it ride.

Would would be interesting (to me) would be to be able to change these via environment variables (for Docker use). I'm still struggling to use the scenario2map argument, but last night was the first time since my prior ticket that I've tried. My OARC server has been running the same map for the intervening months. I'm not going to pursue it until I can dig into it and come back with an actionable bug report that points to the code that needs fixing. 

Closing this for now. Thanks.

**Comment by Oarcinae** [comment]
Yeah let me know what you find with scenario2map, I see no reason that shouldn't work. I still have a bug open on the factorio forums for --map-settings not working in some cases. I hate having to add support for game properties already exposed with --map-settings and --map-gen-settings.

**Comment by bplein** [comment]
Looks like scenario2map is working. Not sure why it was failing for a while. 

All good now!
